const mockProducts = [
  {
    id: 1,
    title: 'Essence Mascara Lash Princess',
    description:
      'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects.',
    price: 9.99,
    rating: 4.94,
    stock: 5,
    brand: 'Essence',
    category: 'beauty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/thumbnail.png',
  },
  {
    id: 2,
    title: 'Eyeshadow Palette with Mirror',
    description:
      'The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for stunning eye looks.',
    price: 19.99,
    rating: 3.28,
    stock: 44,
    brand: 'Glamour Beauty',
    category: 'beauty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Eyeshadow%20Palette%20with%20Mirror/thumbnail.png',
  },
  {
    id: 3,
    title: 'Powder Canister',
    description: 'The Powder Canister is a finely milled setting powder designed to set makeup and control shine.',
    price: 14.99,
    rating: 3.82,
    stock: 59,
    brand: 'Velvet Touch',
    category: 'beauty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Powder%20Canister/thumbnail.png',
  },
  {
    id: 4,
    title: 'Red Lipstick',
    description:
      'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips.',
    price: 12.99,
    rating: 2.51,
    stock: 68,
    brand: 'Chic Cosmetics',
    category: 'beauty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Red%20Lipstick/thumbnail.png',
  },
  {
    id: 5,
    title: 'Red Nail Polish',
    description: 'The Red Nail Polish offers a rich and glossy red hue for vibrant nail color.',
    price: 8.99,
    rating: 3.91,
    stock: 71,
    brand: 'Chic Cosmetics',
    category: 'beauty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Red%20Nail%20Polish/thumbnail.png',
  },
  {
    id: 6,
    title: 'Calvin Klein CK One',
    description: 'CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent.',
    price: 49.99,
    rating: 4.85,
    stock: 17,
    brand: 'Calvin Klein',
    category: 'fragrances',
    thumbnail: 'https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/thumbnail.png',
  },
  {
    id: 7,
    title: 'Chanel Coco Noir Eau De',
    description:
      'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood.',
    price: 129.99,
    rating: 2.76,
    stock: 41,
    brand: 'Chanel',
    category: 'fragrances',
    thumbnail: 'https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/thumbnail.png',
  },
  {
    id: 8,
    title: 'Dior J\'adore',
    description:
      'J\'adore by Dior is a luxurious and feminine fragrance, known for its floral and fruity notes.',
    price: 89.99,
    rating: 3.31,
    stock: 91,
    brand: 'Dior',
    category: 'fragrances',
    thumbnail: 'https://cdn.dummyjson.com/products/images/fragrances/Dior%20J\'adore/thumbnail.png',
  },
  {
    id: 9,
    title: 'Dolce Shine Eau de',
    description:
      'Dolce Shine by Dolce & Gabbana is a vibrant and youthful fragrance, featuring notes of mango, jasmine, and heliotrope.',
    price: 69.99,
    rating: 3.53,
    stock: 3,
    brand: 'Dolce & Gabbana',
    category: 'fragrances',
    thumbnail: 'https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/thumbnail.png',
  },
  {
    id: 10,
    title: 'Gucci Bloom Eau de',
    description:
      'Gucci Bloom by Gucci is a floral and captivating fragrance, featuring notes of tuberose, jasmine, and Rangoon creeper.',
    price: 79.99,
    rating: 2.69,
    stock: 93,
    brand: 'Gucci',
    category: 'fragrances',
    thumbnail: 'https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/thumbnail.png',
  },
  {
    id: 11,
    title: 'Anne Klein Women\'s Watch',
    description: 'The Anne Klein Women\'s Watch features a classic design with a stainless steel bracelet and a round dial.',
    price: 129.99,
    rating: 3.76,
    stock: 50,
    brand: 'Anne Klein',
    category: 'womens-watches',
    thumbnail: 'https://cdn.dummyjson.com/products/images/womens-watches/Anne%20Klein%20Women\'s%20Watch/thumbnail.png',
  },
  {
    id: 12,
    title: 'Fossil Women\'s Watch',
    description: 'The Fossil Women\'s Watch is a stylish and contemporary timepiece with a leather strap.',
    price: 99.99,
    rating: 3.85,
    stock: 33,
    brand: 'Fossil',
    category: 'womens-watches',
    thumbnail: 'https://cdn.dummyjson.com/products/images/womens-watches/Fossil%20Women\'s%20Watch/thumbnail.png',
  },
  {
    id: 13,
    title: 'iPhone 15 Pro',
    description:
      'The iPhone 15 Pro features Apple\'s latest A17 Pro chip, a titanium design, and a 48MP camera system.',
    price: 999.99,
    rating: 4.72,
    stock: 18,
    brand: 'Apple',
    category: 'smartphones',
    thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/iPhone%2015%20Pro/thumbnail.png',
  },
  {
    id: 14,
    title: 'Samsung Galaxy S23 Ultra',
    description:
      'The Samsung Galaxy S23 Ultra has a 200MP camera and the built-in S Pen for note-taking and creative work.',
    price: 1199.99,
    rating: 4.63,
    stock: 9,
    brand: 'Samsung',
    category: 'smartphones',
    thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S23%20Ultra/thumbnail.png',
  },
  {
    id: 15,
    title: 'MacBook Pro 16-inch',
    description:
      'The MacBook Pro 16-inch features the M3 Pro chip with a stunning Liquid Retina XDR display.',
    price: 2499.99,
    rating: 4.88,
    stock: 12,
    brand: 'Apple',
    category: 'laptops',
    thumbnail: 'https://cdn.dummyjson.com/products/images/laptops/MacBook%20Pro%2016-inch/thumbnail.png',
  },
];

export default mockProducts;
